name: Flutter Windows Build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: stable
      
      - name: Check Flutter environment
        run: flutter doctor -v

      - name: Clean project
        run: flutter clean

      - name: 获取依赖
        run: flutter pub get

      - name: Debug Info
        run: |
          flutter --version
          dart --version
          flutter pub deps

      - name: 构建 Windows 应用
        run: flutter build windows --release

      - name: 打包成 ZIP
        shell: pwsh
        run: |
          $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
          Compress-Archive -Path "build/windows/runner/Release/*" -DestinationPath "app-windows-$timestamp.zip"

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: app-windows-*.zip
